server:
  port: 8080
  servlet:
    encoding:
      charset: utf-8
      enabled: true




spring:
  config:
    import:
      - classpath:/config/secret.yml


logging.level:
  org.hibernate.SQL: trace


