on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Configure AWS Credentials
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_KEY }}
          bucket: ${{ secrets.bucket }}
          aws-region: ap-southeast-1

      - name: Deploy static site to S3 bucket
        run: aws s3 sync ./public/ s3://ocfiles-store --delete
